<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <RootNamespace>Grimoire</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Exceptions.PostgreSQL" Version="10.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.7"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.7"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Grimoire.Domain\Grimoire.Domain.csproj"/>
  </ItemGroup>

</Project>
