// <auto-generated />
using System;
using Grimoire.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grimoire.Settings.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20251104231440_RemovingSinIdGeneration")]
    partial class RemovingSinIdGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Settings")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grimoire.Settings.Domain.CustomCommandsSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("GuildId");

                    b.ToTable("CustomCommandsSettings", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettings", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("UserCommandChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("GuildSettings", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("IgnoredChannels", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredMember", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("IgnoredMembers", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredRole", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("RoleId");

                    b.ToTable("IgnoredRoles", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.LevelingSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("Base")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<decimal?>("LevelChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Modifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("TextTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(0, 0, 3, 0, 0));

                    b.HasKey("GuildId");

                    b.ToTable("LevelingSettings", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Lock", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("PreviouslyAllowed")
                        .HasColumnType("bigint");

                    b.Property<long>("PreviouslyDenied")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("ChannelId");

                    b.HasIndex("EndTime");

                    b.ToTable("Locks", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.MessageLogChannelOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ChannelOption")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("MessagesLogChannelOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.MessageLogSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("BulkDeleteChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DeleteChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("EditChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("GuildId");

                    b.ToTable("MessageLogSettings", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ModerationSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AntiSpamEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("AutoPardonAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(10950, 0, 0, 0, 0));

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MuteRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("PublicBanLog")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("ModerationSettings", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Mute", b =>
                {
                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("SinId");

                    b.HasIndex("EndTime");

                    b.ToTable("Mutes", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Reward", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("RewardLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RewardMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId", "RewardLevel");

                    b.ToTable("Rewards", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.SpamFilterOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ChannelOption")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("SpamFilterOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Tracker", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("EndTime");

                    b.ToTable("Trackers", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.UserLogSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AvatarChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("JoinChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("LeaveChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("NicknameChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("UsernameChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("UserLogSettings", "Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
