// <auto-generated />
using System;
using Grimoire.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grimoire.Settings.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260510194155_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Settings")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grimoire.Settings.Domain.ChannelLock", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("ChannelLocks", "Settings");

                    b.HasDiscriminator<string>("EventType").IsComplete(true).HasValue("ChannelLock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSetting", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Type", "GuildId", "SetAt");

                    b.HasIndex("GuildId", "Type", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("GuildSettings", "Settings", t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator<string>("State").IsComplete(true).HasValue("GuildSetting");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.MessageLogChannelOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelOption")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("GuildId");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("MessageLogChannelOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Mute", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId", "SetAt");

                    b.HasIndex("UserId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("Mutes", "Settings");

                    b.HasDiscriminator<string>("EventType").IsComplete(true).HasValue("Mute");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Reward", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId", "RoleId", "SetAt");

                    b.HasIndex("GuildId", "RoleId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("Rewards", "Settings");

                    b.HasDiscriminator<string>("RewardType").IsComplete(true).HasValue("Reward");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.SpamFilterOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelOption")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("GuildId");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("SpamFilterOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ThreadLock", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("ThreadLocks", "Settings");

                    b.HasDiscriminator<string>("EventType").IsComplete(true).HasValue("ThreadLock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.XpTrackedItem", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("GuildId", "Id", "SetAt");

                    b.HasIndex("GuildId", "Id", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("XpTrackedItems", "Settings");

                    b.HasDiscriminator<string>("Type").IsComplete(true).HasValue("XpTrackedItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ChannelLocked", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ChannelLock");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PreviouslyAllowed")
                        .HasColumnType("bigint");

                    b.Property<long>("PreviouslyDenied")
                        .HasColumnType("bigint");

                    b.HasIndex("EndTime");

                    b.HasDiscriminator().HasValue("Locked");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ChannelUnlocked", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ChannelLock");

                    b.HasDiscriminator().HasValue("Unlocked");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingCustomValue", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("CustomValue");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingDefault", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("Default");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingDisabled", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("Disabled");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.MuteAdded", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.Mute");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.HasIndex("EndTime");

                    b.HasDiscriminator().HasValue("Added");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.MuteRemoved", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.Mute");

                    b.HasDiscriminator().HasValue("Removed");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.RewardAdded", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.Reward");

                    b.Property<int>("RewardLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RewardMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasDiscriminator().HasValue("Added");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.RewardRemoved", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.Reward");

                    b.HasDiscriminator().HasValue("Removed");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ThreadLocked", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ThreadLock");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("EndTime");

                    b.HasDiscriminator().HasValue("Locked");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ThreadUnlocked", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ThreadLock");

                    b.HasDiscriminator().HasValue("Unlocked");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredChannel", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpTrackedItem");

                    b.HasDiscriminator().HasValue("IgnoredChannel");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredMember", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpTrackedItem");

                    b.HasDiscriminator().HasValue("IgnoredMember");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredRole", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpTrackedItem");

                    b.HasDiscriminator().HasValue("IgnoredRole");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.WatchedChannel", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpTrackedItem");

                    b.HasDiscriminator().HasValue("WatchedChannel");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.WatchedMember", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpTrackedItem");

                    b.HasDiscriminator().HasValue("WatchedMember");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.WatchedRole", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpTrackedItem");

                    b.HasDiscriminator().HasValue("WatchedRole");
                });
#pragma warning restore 612, 618
        }
    }
}
