// <auto-generated />
using System;
using Grimoire.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grimoire.Settings.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260412151654_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Settings")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSetting", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Type", "GuildId", "SetAt");

                    b.HasIndex("GuildId", "Type", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("GuildSettings", "Settings", t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "\"State\" = 2 AND \"Value\" IS NOT NULL\r\n                OR \"State\" IN (0, 1) AND \"Value\" IS NULL");
                        });

                    b.HasDiscriminator<int>("State");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("IgnoredChannels", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredMember", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("IgnoredMembers", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredRole", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("RoleId");

                    b.ToTable("IgnoredRoles", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Lock", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("PreviouslyAllowed")
                        .HasColumnType("bigint");

                    b.Property<long>("PreviouslyDenied")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("ChannelId");

                    b.HasIndex("EndTime");

                    b.ToTable("Locks", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.MessageLogChannelOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ChannelOption")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("MessagesLogChannelOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Mute", b =>
                {
                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("SinId");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique();

                    b.ToTable("Mutes", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Reward", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("RewardLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RewardMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId", "RewardLevel");

                    b.ToTable("Rewards", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.SpamFilterOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ChannelOption")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("SpamFilterOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Tracker", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("EndTime");

                    b.ToTable("Trackers", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingCustomValue", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "\"State\" = 2 AND \"Value\" IS NOT NULL\r\n                OR \"State\" IN (0, 1) AND \"Value\" IS NULL");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingDefault", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "\"State\" = 2 AND \"Value\" IS NOT NULL\r\n                OR \"State\" IN (0, 1) AND \"Value\" IS NULL");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingDisabled", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "\"State\" = 2 AND \"Value\" IS NOT NULL\r\n                OR \"State\" IN (0, 1) AND \"Value\" IS NULL");
                        });

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
