// <auto-generated />
using System;
using Grimoire.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grimoire.Settings.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260417214145_DataMigration")]
    partial class DataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Settings")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grimoire.Settings.Domain.ChannelLock", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("ChannelLocks", "Settings");

                    b.HasDiscriminator<string>("EventType").IsComplete(true).HasValue("ChannelLock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSetting", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Type", "GuildId", "SetAt");

                    b.HasIndex("GuildId", "Type", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("GuildSettings", "Settings", t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator<string>("State").HasValue("GuildSetting");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.MessageLogChannelOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelOption")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("GuildId");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("MessagesLogChannelOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Mute", b =>
                {
                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("SinId");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique();

                    b.ToTable("Mutes", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Reward", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RewardLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RewardMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId", "RoleId", "SetAt");

                    b.HasIndex("GuildId", "RoleId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("Rewards", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.SpamFilterOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelOption")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("GuildId");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("SpamFilterOverrides", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ThreadLock", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("ChannelId", "GuildId", "SetAt");

                    b.HasIndex("ChannelId", "GuildId", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("ThreadLocks", "Settings");

                    b.HasDiscriminator<string>("EventType").IsComplete(true).HasValue("ThreadLock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.Tracker", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("EndTime");

                    b.ToTable("Trackers", "Settings");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.XpIgnoredItem", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SetBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("GuildId", "Id", "SetAt");

                    b.HasIndex("GuildId", "Id", "SetAt")
                        .IsDescending(false, false, true);

                    b.ToTable("XpIgnoredItems", "Settings");

                    b.HasDiscriminator<string>("Type").HasValue("XpIgnoredItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ChannelLockEvent", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ChannelLock");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PreviouslyAllowed")
                        .HasColumnType("bigint");

                    b.Property<long>("PreviouslyDenied")
                        .HasColumnType("bigint");

                    b.HasIndex("EndTime");

                    b.HasDiscriminator().HasValue("LockEvent");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ChannelUnlockEvent", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ChannelLock");

                    b.HasDiscriminator().HasValue("UnlockEvent");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingCustomValue", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("CustomValue");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingDefault", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("Default");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.GuildSettingDisabled", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.GuildSetting");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_GuildSettings_State_Value", "(\"State\" = 'CustomValue' AND \"Value\" IS NOT NULL)\r\n                OR (\"State\" IN ('Default', 'Disabled') AND \"Value\" IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("Disabled");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ThreadLockEvent", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ThreadLock");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("EndTime");

                    b.HasDiscriminator().HasValue("LockEvent");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.ThreadUnlockEvent", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.ThreadLock");

                    b.HasDiscriminator().HasValue("UnlockEvent");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredChannel", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpIgnoredItem");

                    b.HasDiscriminator().HasValue("Channel");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredMember", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpIgnoredItem");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("Grimoire.Settings.Domain.IgnoredRole", b =>
                {
                    b.HasBaseType("Grimoire.Settings.Domain.XpIgnoredItem");

                    b.HasDiscriminator().HasValue("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
