// <auto-generated />
using System;
using Grimoire;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grimoire.Migrations
{
    [DbContext(typeof(GrimoireDbContext))]
    partial class GrimoireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grimoire.Domain.Attachment", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Avatar", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("UserId", "GuildId", "Timestamp");

                    b.ToTable("Avatars", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.CustomCommand", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Name", "GuildId", "CreatedAt");

                    b.HasIndex("GuildId", "Name");

                    b.ToTable("CustomCommands", (string)null);

                    b.HasDiscriminator<string>("CommandType").IsComplete(true).HasValue("CustomCommand");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Domain.CustomCommandRole", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Name", "GuildId", "CreatedAt", "RoleId");

                    b.ToTable("CustomCommandsRole", (string)null);

                    b.HasDiscriminator<string>("RoleType").IsComplete(true).HasValue("CustomCommandRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Domain.CustomCommandUsage", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name", "GuildId", "UserId", "UsedAt");

                    b.HasIndex("GuildId", "Name", "UsedAt");

                    b.HasIndex("GuildId", "Name", "UserId");

                    b.ToTable("CustomCommandUsages", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.LeaderboardView", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.ToTable((string)null);

                    b.ToView("leaderboard_view", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Message", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ReferencedMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.MessageHistoryEntry", b =>
                {
                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TimeStamp");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("Content");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModeratorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ModeratorId");

                    b.HasKey("MessageId", "Timestamp");

                    b.ToTable("MessageHistory", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("MessageHistoryEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Domain.NicknameHistory", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nickname")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UserId", "GuildId", "Timestamp");

                    b.ToTable("NicknameHistory", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Channel", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModChannelLog")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("UserCommandChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.GuildCommandsSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("GuildId");

                    b.ToTable("GuildCommandsSettings", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.GuildLevelSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("Base")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<decimal?>("LevelChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Modifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("TextTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(0, 0, 3, 0, 0));

                    b.HasKey("GuildId");

                    b.ToTable("GuildLevelSettings", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.GuildMessageLogSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("BulkDeleteChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DeleteChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("EditChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("GuildId");

                    b.ToTable("GuildMessageLogSettings", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.GuildModerationSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AntiSpamEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("AutoPardonAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(10950, 0, 0, 0, 0));

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MuteRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("PublicBanLog")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.HasIndex("MuteRole")
                        .IsUnique();

                    b.ToTable("GuildModerationSettings", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.GuildUserLogSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AvatarChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("JoinChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("LeaveChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ModuleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("NicknameChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("UsernameChannelLogId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildUserLogSettings", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.IgnoredChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("IgnoredChannels", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.IgnoredMember", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("IgnoredMembers", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.IgnoredRole", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("RoleId");

                    b.ToTable("IgnoredRoles", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Lock", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("PreviouslyAllowed")
                        .HasColumnType("bigint");

                    b.Property<long>("PreviouslyDenied")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ChannelId");

                    b.HasIndex("EndTime");

                    b.ToTable("Locks", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Member", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.MessageLogChannelOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ChannelOption")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("MessagesLogChannelOverrides", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Mute", b =>
                {
                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("SinId");

                    b.HasIndex("EndTime");

                    b.ToTable("Mutes", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Reward", b =>
                {
                    b.Property<decimal>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("RewardLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RewardMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId", "RewardLevel");

                    b.ToTable("Rewards", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Role", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.SpamFilterOverride", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ChannelOption")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.ToTable("SpamFilterOverrides", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.OldLogMessage", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("TimesTried")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("OldLogMessages", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Pardon", b =>
                {
                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("SinId", "SetAt");

                    b.HasIndex("SinId", "SetAt")
                        .IsDescending(false, true);

                    b.ToTable("Pardons", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.ProxiedMessageLink", b =>
                {
                    b.Property<decimal>("ProxyMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OriginalMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ProxyMessageId", "OriginalMessageId");

                    b.HasIndex("OriginalMessageId")
                        .IsUnique();

                    b.HasIndex("ProxyMessageId")
                        .IsUnique();

                    b.ToTable("ProxiedMessages", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.PublishedMessage", b =>
                {
                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.Property<int>("PublishType")
                        .HasColumnType("integer");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("SinId", "PublishType");

                    b.ToTable("PublishedMessages", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.Sin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Actor")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ModeratorId");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SinOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("SinType")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "GuildId")
                        .HasDatabaseName("IX_Sin_Id_GuildId");

                    b.HasIndex("Actor", "GuildId", "SinType")
                        .HasDatabaseName("IX_Sin_ModeratorId_GuildId_SinType");

                    b.HasIndex("UserId", "GuildId", "SinOn")
                        .HasDatabaseName("IX_Sin_UserId_GuildId_SinOn");

                    b.ToTable("Sins", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.SinReasonHistory", b =>
                {
                    b.Property<long>("SinId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Actor")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ModeratorId");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("SinId", "SetAt");

                    b.HasIndex("SinId", "SetAt")
                        .IsDescending(false, true);

                    b.ToTable("SinReasonHistory", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.UsernameHistory", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(37)
                        .HasColumnType("character varying(37)");

                    b.HasKey("UserId", "Timestamp");

                    b.ToTable("UsernameHistory", (string)null);
                });

            modelBuilder.Entity("Grimoire.Domain.XpHistoryEntry", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("TimeOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RawXp")
                        .HasColumnType("bigint")
                        .HasColumnName("Xp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("UserId", "GuildId", "TimeOut");

                    b.HasIndex("GuildId", "RawXp")
                        .HasDatabaseName("IX_XpHistory_GuildId_Xp");

                    b.HasIndex("UserId", "GuildId", "RawXp")
                        .HasDatabaseName("IX_XpHistory_UserId_GuildId_Xp");

                    b.ToTable("XpHistory", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("XpHistoryEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Grimoire.Domain.EmbedCustomCommand", b =>
                {
                    b.HasBaseType("Grimoire.Domain.CustomCommand");

                    b.Property<string>("EmbedColor")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasDiscriminator().HasValue("Embed");
                });

            modelBuilder.Entity("Grimoire.Domain.TextCustomCommand", b =>
                {
                    b.HasBaseType("Grimoire.Domain.CustomCommand");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("Grimoire.Domain.CustomCommandAllowRole", b =>
                {
                    b.HasBaseType("Grimoire.Domain.CustomCommandRole");

                    b.HasDiscriminator().HasValue("Allow");
                });

            modelBuilder.Entity("Grimoire.Domain.CustomCommandDenyRole", b =>
                {
                    b.HasBaseType("Grimoire.Domain.CustomCommandRole");

                    b.HasDiscriminator().HasValue("Deny");
                });

            modelBuilder.Entity("Grimoire.Domain.MessageCreatedEntry", b =>
                {
                    b.HasBaseType("Grimoire.Domain.MessageHistoryEntry");

                    b.HasDiscriminator().HasValue("Created");
                });

            modelBuilder.Entity("Grimoire.Domain.MessageDeletedByModeratorEntry", b =>
                {
                    b.HasBaseType("Grimoire.Domain.MessageHistoryEntry");

                    b.HasDiscriminator().HasValue("DeletedByModerator");
                });

            modelBuilder.Entity("Grimoire.Domain.MessageDeletedEntry", b =>
                {
                    b.HasBaseType("Grimoire.Domain.MessageHistoryEntry");

                    b.HasDiscriminator().HasValue("Deleted");
                });

            modelBuilder.Entity("Grimoire.Domain.MessageEditedEntry", b =>
                {
                    b.HasBaseType("Grimoire.Domain.MessageHistoryEntry");

                    b.HasDiscriminator().HasValue("Edited");
                });

            modelBuilder.Entity("Grimoire.Domain.AwardedXp", b =>
                {
                    b.HasBaseType("Grimoire.Domain.XpHistoryEntry");

                    b.Property<decimal>("AwarderId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("AwarderId");

                    b.HasDiscriminator().HasValue("Awarded");
                });

            modelBuilder.Entity("Grimoire.Domain.EarnedXp", b =>
                {
                    b.HasBaseType("Grimoire.Domain.XpHistoryEntry");

                    b.HasDiscriminator().HasValue("Earned");
                });

            modelBuilder.Entity("Grimoire.Domain.MigratedXp", b =>
                {
                    b.HasBaseType("Grimoire.Domain.XpHistoryEntry");

                    b.HasDiscriminator().HasValue("Migrated");
                });

            modelBuilder.Entity("Grimoire.Domain.ReclaimedXp", b =>
                {
                    b.HasBaseType("Grimoire.Domain.XpHistoryEntry");

                    b.HasDiscriminator().HasValue("Reclaimed");
                });

            modelBuilder.Entity("Grimoire.Domain.Attachment", b =>
                {
                    b.HasOne("Grimoire.Domain.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Grimoire.Domain.CustomCommandRole", b =>
                {
                    b.HasOne("Grimoire.Domain.CustomCommand", "CustomCommand")
                        .WithMany("Roles")
                        .HasForeignKey("Name", "GuildId", "CreatedAt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomCommand");
                });

            modelBuilder.Entity("Grimoire.Domain.MessageHistoryEntry", b =>
                {
                    b.HasOne("Grimoire.Domain.Message", "Message")
                        .WithMany("MessageHistory")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.GuildModerationSettings", b =>
                {
                    b.HasOne("Grimoire.Domain.Obsolete.Role", "MuteRoleNav")
                        .WithOne()
                        .HasForeignKey("Grimoire.Domain.Obsolete.GuildModerationSettings", "MuteRole");

                    b.Navigation("MuteRoleNav");
                });

            modelBuilder.Entity("Grimoire.Domain.Obsolete.Role", b =>
                {
                    b.HasOne("Grimoire.Domain.Obsolete.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Grimoire.Domain.Pardon", b =>
                {
                    b.HasOne("Grimoire.Domain.Sin", "Sin")
                        .WithMany("Pardons")
                        .HasForeignKey("SinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sin");
                });

            modelBuilder.Entity("Grimoire.Domain.ProxiedMessageLink", b =>
                {
                    b.HasOne("Grimoire.Domain.Message", "OriginalMessage")
                        .WithOne("OriginalMessageLink")
                        .HasForeignKey("Grimoire.Domain.ProxiedMessageLink", "OriginalMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grimoire.Domain.Message", "ProxyMessage")
                        .WithOne("ProxiedMessageLink")
                        .HasForeignKey("Grimoire.Domain.ProxiedMessageLink", "ProxyMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalMessage");

                    b.Navigation("ProxyMessage");
                });

            modelBuilder.Entity("Grimoire.Domain.PublishedMessage", b =>
                {
                    b.HasOne("Grimoire.Domain.Sin", "Sin")
                        .WithMany("PublishMessages")
                        .HasForeignKey("SinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sin");
                });

            modelBuilder.Entity("Grimoire.Domain.SinReasonHistory", b =>
                {
                    b.HasOne("Grimoire.Domain.Sin", "Sin")
                        .WithMany("ReasonHistory")
                        .HasForeignKey("SinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sin");
                });

            modelBuilder.Entity("Grimoire.Domain.CustomCommand", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Grimoire.Domain.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("MessageHistory");

                    b.Navigation("OriginalMessageLink");

                    b.Navigation("ProxiedMessageLink");
                });

            modelBuilder.Entity("Grimoire.Domain.Sin", b =>
                {
                    b.Navigation("Pardons");

                    b.Navigation("PublishMessages");

                    b.Navigation("ReasonHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
